// -----------------------------------------------------------------------------
// FOOTER
// -----------------------------------------------------------------------------
//
// Displays the Admindash3 build/version information.
//
// The version is assembled from compile-time environment variables:
//
//     CARGO_PKG_VERSION
//         The application version from Cargo.toml.
//
//     GIT_HASH
//         The short Git commit hash, generated by build.rs.
//
//     RUSTC_VERSION
//         The Rust compiler version used to compile this build, also generated
//         by build.rs.
//
// Example:
//
//     Admindash3 v1.0.0-a83f91c; compiled with rust v1.92.0
//
// IMPORTANT:
//
// These are compile-time environment variables.
//
// That means the information is baked into the application when Cargo builds
// it. We do NOT need:
//
//     - a signal
//     - a server function
//     - an HTTP request
//     - JavaScript
//
// The exact same build information can therefore be displayed by SSR and WASM.
// -----------------------------------------------------------------------------

use dioxus::prelude::*;

//
// -----------------------------------------------------------------------------
// FOOTER COMPONENT
// -----------------------------------------------------------------------------
//

#[component]
pub fn Footer() -> Element {
    // -------------------------------------------------------------------------
    // Build the application version string.
    //
    // CARGO_PKG_VERSION comes directly from Cargo.toml.
    //
    // GIT_HASH is created by build.rs using:
    //
    //     git rev-parse --short HEAD
    //
    // RUSTC_VERSION is created by build.rs using the rustc_version crate.
    //
    // Example final string:
    //
    //     1.0.0-a83f91c; compiled with rust v1.92.0
    //
    // We use concat!() here because all three values are compile-time
    // environment variables.
    // -------------------------------------------------------------------------

    let version = concat!(
        env!("CARGO_PKG_VERSION"),
        "-",
        env!("GIT_HASH"),
        "; compiled with rust v",
        env!("RUSTC_VERSION")
    );

    // -------------------------------------------------------------------------
    // RENDER FOOTER
    // -------------------------------------------------------------------------

    rsx! {

        footer {
            // Keep the footer as a fixed-height sibling of the scrolling
            // main area.  The parent page uses a viewport-sized flex column.
            class: "w-full shrink-0 mt-8 py-4
                    border-t border-gray-700
                    bg-gray-900
                    text-gray-400
                    text-sm
                    text-center",

            "Admindash3 v{version}"
        }

    }
}
